### ISSUE TITLE
Is this for automatic type-hinting in python?

### ISSUE THREAD

**Issue by codelif** [exitflynn/autotyping-pre-commit#1]
If so, will you be building your own syntax tree and parser or maybe there is already a tool available and this project just builds a pre-commit hook?

**Comment by exitflynn** [comment]
hey, this totally slipped my mind, i found out there's quite [some](https://github.com/JelleZijlstra/autotyping/) [tools](https://github.com/Instagram/MonkeyType) that do that already and are awesome at it, so it's more of the latter than the former now, and I'll be deleting the repo soon.

what you mean by the syntax tree though, most tools in this ballpark use [LibCST](https://github.com/Instagram/LibCST) to take care of the python AST
